name: Colin M. Brand

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
theme: minima

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        publications:
                output: true
        